version: "3.2"

services:
  php-apache:
    build: ./docker/php
    container_name: lr_boilerplate
    environment:
      - APACHE_RUN_USER=#1000
    ports:
      - 8080:80
    volumes:
      - ./web:/var/www/html
    links:
      - mysql_db

  mysql_db:
    image: mariadb
    restart: always
    volumes:
      - ./docker/data:/var/lib/mysql
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD : test123
        MYSQL_ROOT_PASSWORD: test123
        MYSQL_DATABASE: boilerplate_db

  boilerplate_sql_ui:
    image: phpmyadmin/phpmyadmin
    container_name: boilerplate_sql_ui
    depends_on:
      - mysql_db
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 3080:80
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: test123


  nodejs:
    image: node:latest
    command: /bin/bash -c "npm run watch"
    container_name: nodejs
    working_dir: /var/www/html/
    ports:
      - 5000:80
    volumes:
      - ./web:/var/www/html/
