export const authConstants = {
    REGISTER_REQUEST_LOADING: "REGISTER_REQUEST_LOADING",
    REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
    REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

    LOGIN_REQUEST_LOADING: "LOGIN_REQUEST_LOADING",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    LOGOUT: "USERS_LOGOUT"
};
