export const buttonActiveConstants = {
    BUTTONACTIVE_REQUEST_LOADING: "BUTTONACTIVE_REQUEST_LOADING",
    BUTTONACTIVE_SUCCESS: "BUTTONACTIVE_SUCCESS",
    BUTTONACTIVE_FAILURE: "BUTTONACTIVE_FAILURE"
};
