export const profSettingsConstants = {
    PROFILE_SETTINGS_LOADING: "PROFILE_SETTINGS_LOADING",
    PROFILE_SETTINGS_SUCCESS: "PROFILE_SETTINGS_SUCCESS",
    PROFILE_SETTINGS_FAILURE: "PROFILE_SETTINGS_FAILURE"
};
