export const usersBirthdaysConstants = {
    USERS_BIRTHDAYS_REQUEST_LOADING: "USERS_BIRTHDAYS_REQUEST_LOADING",
    USERS_BIRTHDAYS_SUCCESS: "USERS_BIRTHDAYS_SUCCESS",
    USERS_BIRTHDAYS_FAILURE: "USERS_BIRTHDAYS_FAILURE"
};
