export const vocationonstants = {
    VOCATION_REQUEST_LOADING: "VOCATION_REQUEST_LOADING",
    VOCATION_REQUEST_SUCCESS: "VOCATION_REQUEST",
    VOCATION_REQUEST_FAILURE: "VOCATION_REQUEST_FAILURE",

    GET_ALL_VACATION_LOADING: "GET_ALL_VACATION_LOADING",
    GET_ALL_VACATION_SUCCESS: "GET_ALL_VACATION_SUCCESS",
    GET_ALL_VACATION_FAILURE: "GET_ALL_VACATION_FAILURE"
};
